import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './styles/globals.css'
import { NotificationProvider } from './context/notificationContext'

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700', '800'],
	display: 'swap',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='pt-BR'>
			<body
				className={`${poppins.className} bg-background text-foreground antialiased`}
			>
				<NotificationProvider>{children}</NotificationProvider>
			</body>
		</html>
	)
}
